export const ORDER_CREATE_REQ = 'ORDER_CREATE_REQ'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_ERR = 'ORDER_CREATE_ERR'

export const ORDER_INFO_REQ = 'ORDER_INFO_REQ'
export const ORDER_INFO_SUCCESS = 'ORDER_INFO_SUCCESS'
export const ORDER_INFO_ERR = 'ORDER_INFO_ERR'

export const ORDER_PAY_REQ = 'ORDER_PAY_REQ'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_ERR = 'ORDER_PAY_ERR'

export const ORDER_PAY_RESET = 'ORDER_RESET'

export const ORDER_LIST_REQ = 'ORDER_LIST_REQ'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_ERR = 'ORDER_LIST_ERR'