export const PRODUCT_LIST_REQ = 'PRODUCT_LIST_REQ'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_ERR = 'PRODUCT_LIST_ERR'

export const PRODUCT_REQ = 'PRODUCT_REQ'
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS'
export const PRODUCT_ERR = 'PRODUCT_ERR'

export const PRODUCT_DELETE_REQ = 'PRODUCT_DELETE_REQ'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_ERR = 'PRODUCT_DELETE_ERR'

export const PRODUCT_CREATE_REQ = 'PRODUCT_CREATE_REQ'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_ERR = 'PRODUCT_CREATE_ERR'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_EDIT_REQ = 'PRODUCT_EDIT_REQ'
export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS'
export const PRODUCT_EDIT_ERR = 'PRODUCT_EDIT_ERR'
export const PRODUCT_EDIT_RESET = 'PRODUCT_EDIT_RESET'

export const PRODUCT_ADD_REVIEW_REQ = 'PRODUCT_ADD_REVIEW_REQ'
export const PRODUCT_ADD_REVIEW_SUCCESS = 'PRODUCT_ADD_REVIEW_SUCCESS'
export const PRODUCT_ADD_REVIEW_ERR = 'PRODUCT_ADD_REVIEW_ERR'
export const PRODUCT_ADD_REVIEW_RESET = 'PRODUCT_ADD_REVIEW_RESET'