export const PRODUCT_LIST_REQ = 'PRODUCT_LIST_REQ'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_ERR = 'PRODUCT_LIST_ERR'

export const PRODUCT_REQ = 'PRODUCT_REQ'
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS'
export const PRODUCT_ERR = 'PRODUCT_ERR'