export const USER_LOGIN_REQ = 'USER_LOGIN_REQ'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERR = 'USER_LOGIN_ERR'

export const USER_REGISTER_REQ = 'USER_REGISTER_REQ'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_ERR = 'USER_REGISTER_ERR'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_PROFILE_REQ = 'USER_PROFILE_REQ'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_ERR = 'USER_PROFILE_ERR'

export const USER_PROFILE_UPDATE_REQ = 'USER_PROFILE_UPDATE_REQ'
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS'
export const USER_PROFILE_UPDATE_ERR = 'USER_PROFILE_UPDATE_ERR'
export const USER_PROFILE_UPDATE_RESET = 'USER_PROFILE_UPDATE_RESET'