export const USER_LOGIN_REQ = 'USER_LOGIN_REQ'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERR = 'USER_LOGIN_ERR'

export const USER_REGISTER_REQ = 'USER_REGISTER_REQ'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_ERR = 'USER_REGISTER_ERR'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_PROFILE_REQ = 'USER_PROFILE_REQ'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_ERR = 'USER_PROFILE_ERR'
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET'

export const USER_PROFILE_UPDATE_REQ = 'USER_PROFILE_UPDATE_REQ'
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS'
export const USER_PROFILE_UPDATE_ERR = 'USER_PROFILE_UPDATE_ERR'
export const USER_PROFILE_UPDATE_RESET = 'USER_PROFILE_UPDATE_RESET'

export const USER_LIST_REQ = 'USER_LIST_REQ'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_ERR = 'USER_LIST_ERR'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_DELETE_REQ = 'USER_DELETET_REQ'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_ERR = 'USER_DELETE_ERR'

export const USER_EDIT_REQ = 'USER_EDIT_REQ'
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS'
export const USER_EDIT_ERR = 'USER_EDIT_ERR'
